# Generated by Django 3.2.8 on 2023-07-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0003_packegeresort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packegeresort',
            name='Resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelaid.resort'),
        ),
    ]
