# Generated by Django 3.2.8 on 2023-07-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0006_auto_20230715_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcommunity',
            name='Chatcommunitystatus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatcommunity',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatcommunity',
            name='Chat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatcommunity',
            name='Createdtime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatcommunity',
            name='Uploaddate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
