# Generated by Django 3.2.8 on 2023-07-17 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0008_auto_20230715_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reelslength', models.CharField(max_length=50)),
                ('Reels', models.FileField(null=True, upload_to='images/')),
                ('Description', models.CharField(max_length=50)),
                ('Spotname', models.CharField(max_length=50)),
                ('Uploaddate', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelaid.user')),
            ],
        ),
    ]
