# Generated by Django 3.2.8 on 2023-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0010_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='Checkintime',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='noofpersons',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
