# Generated by Django 3.2.8 on 2023-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0011_auto_20230717_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='Hotel',
            new_name='Hotels',
        ),
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='Hotelname',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='username',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='Bookingstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='Checkindate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='Checkintime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='Checkoutdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='noofpersons',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
