# Generated by Django 3.2.8 on 2023-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0013_auto_20230717_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelbooking',
            old_name='Hotel',
            new_name='hotel',
        ),
    ]
