# Generated by Django 3.2.8 on 2023-07-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0015_resortbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resortbooking',
            old_name='Bookingstatus',
            new_name='bookingstatus',
        ),
        migrations.RenameField(
            model_name='resortbooking',
            old_name='Checkindate',
            new_name='checkindate',
        ),
        migrations.RenameField(
            model_name='resortbooking',
            old_name='Checkintime',
            new_name='checkintime',
        ),
        migrations.RenameField(
            model_name='resortbooking',
            old_name='Checkoutdate',
            new_name='checkoutdate',
        ),
    ]
