# Generated by Django 3.2.8 on 2023-07-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0016_auto_20230717_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotelbooking',
        ),
    ]
