# Generated by Django 3.2.8 on 2023-07-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelaid', '0017_delete_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotelbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(max_length=50)),
                ('noofpersons', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('checkindate', models.CharField(max_length=50)),
                ('checkintime', models.CharField(max_length=50)),
                ('checkoutdate', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('bookingstatus', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelaid.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelaid.user')),
            ],
        ),
    ]
